# Generated by Django 3.2.4 on 2024-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='tartas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
